package br.gohan.pizzacmp.ui.theme
import androidx.compose.ui.graphics.Color


val primaryLight = Color(0xFF823B2B)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFAF5E4C)
val onPrimaryContainerLight = Color(0xFFFFFFFF)
val secondaryLight = Color(0xFF6D5B4E)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFD9C0B0)
val onSecondaryContainerLight = Color(0xFF413226)
val tertiaryLight = Color(0xFF665D50)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFE5D9C9)
val onTertiaryContainerLight = Color(0xFF4A4236)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFFF8F6)
val onBackgroundLight = Color(0xFF221A18)
val surfaceLight = Color(0xFFFDF8F7)
val onSurfaceLight = Color(0xFF1C1B1B)
val surfaceVariantLight = Color(0xFFEBE1D7)
val onSurfaceVariantLight = Color(0xFF4B463F)
val outlineLight = Color(0xFF7D766E)
val outlineVariantLight = Color(0xFFCEC5BC)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF32302F)
val inverseOnSurfaceLight = Color(0xFFF5F0EE)
val inversePrimaryLight = Color(0xFFFFB4A4)
val surfaceDimLight = Color(0xFFDDD9D7)
val surfaceBrightLight = Color(0xFFFDF8F7)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF7F3F1)
val surfaceContainerLight = Color(0xFFF2EDEB)
val surfaceContainerHighLight = Color(0xFFECE7E5)
val surfaceContainerHighestLight = Color(0xFFE6E1E0)

